import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Financial Disclaimer — TerraMind",
  description: "Important disclosures regarding TerraMind's financial intelligence features.",
};

export default function FinancialDisclaimerPage() {
  return (
    <LegalPage title="Financial Disclaimer" lastUpdated="5 June 2026">
      <p>
        TerraMind is a data-driven decision-support platform for New Zealand horticultural
        growers. It provides probabilistic predictions, economic projections, and computed
        recommendations to help growers make informed operational decisions.
      </p>
      <p>
        <strong>
          TerraMind does not provide personalised financial advice, investment advice, tax
          advice, or insurance advice.
        </strong>
      </p>
      <p>
        TerraMind Limited is not a registered financial advice provider under the Financial
        Markets Conduct Act 2013 (NZ). Our outputs do not constitute a "financial advice
        service" as defined in that Act.
      </p>

      <hr />

      <h2>What TerraMind outputs are</h2>
      <p>
        TerraMind outputs are <strong>calculations</strong>, not <strong>opinions</strong>.
        Specifically:
      </p>
      <ul>
        <li>
          <strong>Predictions</strong> are probability distributions generated by statistical
          and agronomic models using publicly available weather, satellite, soil, and terrain
          data. They represent our models' best estimate of what may happen, expressed with
          explicit uncertainty.
        </li>
        <li>
          <strong>Economic projections</strong> are arithmetic translations of predictions into
          dollar terms using published industry parameters (market prices, production costs,
          damage curves) and any grower-customised cost assumptions. They show what the
          predictions mean financially.
        </li>
        <li>
          <strong>Recommendations</strong> are computed comparisons of the expected value of
          available actions (e.g., "run wind machines" vs. "do nothing"). The recommended
          option is the one with the highest computed net expected value. Confidence levels
          (high, medium, marginal) indicate how clear the computation is.
        </li>
      </ul>
      <p>
        None of these outputs account for your full financial circumstances, tax position,
        insurance arrangements, lending covenants, personal risk tolerance, or any other
        factors that a professional financial adviser would consider.
      </p>

      <hr />

      <h2>Limitations you should understand</h2>

      <h3>Predictions are uncertain</h3>
      <p>
        Every prediction is a probability distribution, not a guarantee. When TerraMind says
        "73% probability of frost tonight," it means our models estimate frost will occur in
        roughly 73 out of 100 similar scenarios. The other 27% of the time, frost will not
        occur. Acting on a 73% probability and experiencing the 27% outcome is not a
        prediction failure — it is how probability works.
      </p>

      <h3>Models have known limitations</h3>
      <p>
        Our calibration page at terramind.co.nz/calibration publishes how accurate our
        predictions have been historically, with full reliability diagrams and sample sizes.
        Some prediction types have limited historical validation data, especially early in the
        platform's life. We are transparent about this.
      </p>

      <h3>Economic parameters may not match your situation</h3>
      <p>
        Default economic parameters (market prices, production costs, damage curves) come from
        published industry sources and may not reflect your specific orchard's economics. You
        can customise these parameters in your account settings. The accuracy of financial
        projections depends on the accuracy of these parameters.
      </p>

      <h3>AI-mediated reasoning is exploratory</h3>
      <p>
        The "Ask TerraMind" feature uses large language model technology. Its outputs are
        clearly labelled as "AI reasoning — answers may be unreliable" and are visually
        distinct from calibrated structured-model predictions. Do not rely on AI-mediated
        outputs for consequential decisions without independent verification.
      </p>

      <hr />

      <h2>Your responsibility</h2>
      <p>
        <strong>All operational and financial decisions are yours.</strong>
      </p>
      <p>
        TerraMind presents information and computed options. You decide what to do based on
        your full knowledge of your operation, circumstances, risk tolerance, and professional
        advice.
      </p>
      <p>We strongly recommend that you:</p>
      <ul>
        <li>Consult a qualified financial adviser for financial planning decisions</li>
        <li>Consult a qualified agronomist for crop management decisions</li>
        <li>Consult your accountant for tax-related decisions</li>
        <li>Review your insurance arrangements with your broker</li>
        <li>
          Use TerraMind outputs as one input among many, not as the sole basis for decisions
        </li>
      </ul>

      <hr />

      <h2>Grower opt-out</h2>
      <p>
        If you prefer to receive TerraMind's prediction and financial data without computed
        recommendations, you can disable recommendations in your account settings. The
        underlying data and projections remain available; only the computed "recommended
        action" framing is removed.
      </p>

      <hr />

      <h2>Contact</h2>
      <p>
        If you have questions about this disclaimer or how TerraMind outputs should be
        interpreted:
      </p>
      <ul>
        <li>
          <strong>Email:</strong>{" "}
          <a href="mailto:support@terramind.co.nz">support@terramind.co.nz</a>
        </li>
      </ul>
    </LegalPage>
  );
}
